### ISSUE TITLE
PhidgetAdvancedServo board

### ISSUE THREAD

**Issue by halfpt** [evantahler/nodePhidgets#16]
Hi,

Wanted to say thanks for the awesome work you have done on this project so far - much appreciated.
I was wondering if you had any plans to add servo board control or whether you might consider it as the next board to support? It would be very useful for an upcoming project.

http://www.phidgets.com/products.php?category=11&product_id=1061_1
Many thanks.

**Comment by cotejp** [comment]
Hi Tom,

I'd happily do it but I do not have this board on hand. If this is for a commercial project perhaps you'd be willing to support the development effort? If not, it'll have to wait until I can get my hands on one.

Cheers!

**Comment by evantahler** [comment]
I don't have one of those either :( 

There's another node + phidgets package (which started as a fork of this one) which does have support for some of the other boards: https://github.com/RIAEvangelist/node-phidget-API  There might be some good examples there.

**Comment by halfpt** [comment]
Hi both,

Thanks for your replies. It is not a commercial project, but a side hacking project that I was planning on playing about with. Thanks for the link - if I do go ahead and buy a servo controller I'd have a look at the examples you have posted as a starting point for contributing, at this point though I'm just researching ways to control phidgets in a nodejs environment.

Thanks again for the pointers.
Tom.
