### ISSUE TITLE
Won't connect to multiple boards

### ISSUE THREAD

**Issue by gruppler** [evantahler/nodePhidgets#5]
This works great when I'm using only one board. However, I can't get it to connect to multiple boards. I can see all the boards in the Phidget Control Panel, and I've tried stopping and restarting both the webservice and the node app.

It seems to connect only to the board that was last attached. If I unplug the board that the node app currently sees, it will then connect to the other board, but when I plug the original in again, the node app doesn't reconnect to it. In other words, it will only connect to one board at a time, and that board is the one that was last plugged in.

**Comment by evantahler** [comment]
We just had a major refactor thanks to https://github.com/evantahler/nodePhidgets/pull/8.  The API is changed siginifangly now, but this should be solved.
